language: cpp

sudo: required

dist: trusty

addons:
  apt:
    source:
      - sourceline: 'ppa:george-edison55/cmake-3.x'
    packages:
      - cmake
      - libssl-dev

compiler:
  - clang
  - gcc

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  # - make test

notifications:
  email: false
