language: cpp

sudo: required

dist: trusty

addons:
  apt:
    source:
      - sourceline: 'ppa:george-edison55/cmake-3.x'
      - sourceline: 'ppa:boost-latest/ppa'
    packages:
      - cmake
      - libssl-dev
      - libboost-all-dev

compiler:
  - clang
  - gcc

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  # - make test

notifications:
  email: false
